# Default values for services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: quay.io
  repository: kiali
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # privileged: false

service:
  type: ClusterIP
  port: 8000
  name: http

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

appVersion: v1
appEnv: dev


# Defining deployment environment variables for portal microservices. The env section for the
# control application is empty by default to allow us to use `with` function. You may add additional
# env vars if necessary, but ootb it is not required.
apps:
  - name: voyages
    env:
      coordinates: 48.861310,2.337418
      country: France
      countryShort: fr
  - name: viaggi
    env:
      coordinates: 41.890668,12.492194
      country: Italy
      countryShort: it
  - name: travels
    env:
      coordinates: 55.956245,-3.187915
      country: United Kingdom
      countryShort: uk
  - name: control
    env:
