{{- range $apps := .Values.apps }}
{{ $version := $.Values.appVersion }}
{{ $env := $.Values.appEnv }}
{{- with $img := $.Values.image }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $apps.name }}-{{ $version }}
spec:
  selector:
    matchLabels:
      app: {{ $apps.name }}
      version: {{ $version }}
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- include "travel-agency.istioProxyConfig" . | nindent 8 }}
      labels:
        app: {{ $apps.name }}
        version: {{ $version }}
    spec:
      containers:
        - name: {{ $apps.name }}
          image: {{ $img.registry }}/{{ $img.repository }}/demo_travels_{{ $apps.name }}:{{ $img.tag }}
          imagePullPolicy: {{ $img.pullPolicy }}
{{- end }}
          ports:
            - containerPort: {{ $.Values.service.port }}
          securityContext:
            privileged: false
          env:
            - name: CURRENT_SERVICE
              value: {{ $apps.name }}
            - name: CURRENT_VERSION
              value: {{ $version }}
            - name: LISTEN_ADDRESS
              value: ":8000"
          {{- if ne $apps.name "discounts" }}
            - name: DISCOUNTS_SERVICE
              value: "http://discounts.{{ $env }}-travel-agency:8000"
            - name: MYSQL_SERVICE
              value: "mysqldb.{{ $env }}-travel-agency:3306"
          {{- include "travel-agency.mysqlEnv" . | nindent 12 }}
          {{- end }}
          {{- if eq $apps.name "travels" }}
            - name: FLIGHTS_SERVICE
              value: "http://flights.{{ $env }}-travel-agency:8000"
            - name: HOTELS_SERVICE
              value: "http://hotels.{{ $env }}-travel-agency:8000"
            - name: CARS_SERVICE
              value: "http://cars.{{ $env }}-travel-agency:8000"
            - name: INSURANCES_SERVICE
              value: "http://insurances.{{ $env }}-travel-agency:8000"
          {{- end }}

{{- end }}
