{{- range $apps := .Values.apps }}
{{ $version := $.Values.appVersion }}
{{- with $img := $.Values.image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $apps.name }}-{{ $version }}
spec:
  selector:
    matchLabels:
      app: {{ $apps.name }}
      version: {{ $version }}
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      {{- if $.Values.sidecarAutoInjection }}
        sidecar.istio.io/inject: "true"
      {{- end }}
      {{- if $.Values.sidecarJaeger }}
        sidecar.jaegertracing.io/inject: {{ $.Values.global.jaeger.name | quote }}
      {{- end }}
      {{- if ne $apps.name "insurances" }}
      {{- include "travel-agency.istioProxyConfig" . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $apps.name }}
        version: {{ $version }}
    spec:
      containers:
        - name: {{ $apps.name }}
          image: {{ $img.registry }}/{{ $img.repository }}/demo_travels_{{ $apps.name }}:{{ $img.tag }}
          imagePullPolicy: {{ $img.pullPolicy }}
{{- end }}
          ports:
            - containerPort: {{ $.Values.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: CURRENT_SERVICE
              value: {{ $apps.name }}
            - name: CURRENT_VERSION
              value: {{ $version }}
            - name: LISTEN_ADDRESS
              value: ":8000"
          {{- if eq $apps.name "travels" }}
            - name: FLIGHTS_SERVICE
              value: "http://flights.travel-agency:8000"
            - name: HOTELS_SERVICE
              value: "http://hotels.travel-agency:8000"
            - name: CARS_SERVICE
              value: "http://cars.travel-agency:8000"
            - name: INSURANCES_SERVICE
              value: "http://insurances.travel-agency:8000"
          {{- end }}
          {{- if and ( ne $apps.name "discounts" ) ( ne $apps.name "travels" ) }}
            - name: DISCOUNTS_SERVICE
              value: "http://discounts.travel-agency:8000"
            - name: MYSQL_SERVICE
              value: "mysqldb.travel-agency:3306"
          {{- include "travel-agency.mysqlEnv" . | nindent 12 }}
          {{- end }}

{{- end }}
