apiVersion: networking.istio.io/v1alpha3
metadata:
  name: control
  namespace: {{ .Values.appEnv }}-travel-control
spec:
  host: control.{{ .Values.appEnv }}-travel-control.svc.cluster.local
  subsets:
    - labels:
        version: v1
      name: v1