# Default values for servicemesh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  localClusterDomain: ''

appEnv: dev

#Jaeger tracing configuration
tracing:
  sampling: 10000

#Jaeger Config
jaeger:
  strategy: production
  storage:
    type: elasticsearch
    days: 7 #retention
    schedule: '55 23 * * *'
  elastic:
    nodeCount: 1
    storageSize: 1Gi
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        memory: 2Gi

#Service Mesh ControlPlane version
version: v2.4

#mutual TLS (mTLS)configuration
security:
  controlPlane:
    mtls: true
  dataPlane:
    automtls: true
    mtls: true

# ServiceMesh Membership 
# This generates a serviceMeshMembership in each component namespace
members:
  - agency 
  - control
  - portal
